In [78]:
import pandas as pd
import numpy as np

ind1 = pd.date_range('2017-01-01 00:00:01', freq='H', periods=10)
ind2 = pd.date_range('2017-01-01 00:00:00', freq='2H', periods=5)

data1 = pd.DataFrame({'val1': np.random.rand(10)},
                     index=ind1)
data2 = pd.DataFrame({'val2': np.random.rand(5)},
                     index=ind2)

In [79]:
data1

val1
2017-01-01 00:00:01  0.893037
2017-01-01 01:00:01  0.049925
2017-01-01 02:00:01  0.837652
2017-01-01 03:00:01  0.143972
2017-01-01 04:00:01  0.146704
2017-01-01 05:00:01  0.462497
2017-01-01 06:00:01  0.661669
2017-01-01 07:00:01  0.654570
2017-01-01 08:00:01  0.744998
2017-01-01 09:00:01  0.663441

In [80]:
data2

val2
2017-01-01 00:00:00  0.065677
2017-01-01 02:00:00  0.994933
2017-01-01 04:00:00  0.925059
2017-01-01 06:00:00  0.269661
2017-01-01 08:00:00  0.528682

In [87]:
data1['old_ind'] = data1.index
data1_new = data1.reindex(data2.index, method='nearest')
data1_new

val1             old_ind
2017-01-01 00:00:00  0.893037 2017-01-01 00:00:01
2017-01-01 02:00:00  0.837652 2017-01-01 02:00:01
2017-01-01 04:00:00  0.146704 2017-01-01 04:00:01
2017-01-01 06:00:00  0.661669 2017-01-01 06:00:01
2017-01-01 08:00:00  0.744998 2017-01-01 08:00:01

In [88]:
data2.join(data1_new)

val2      val1             old_ind
2017-01-01 00:00:00  0.065677  0.893037 2017-01-01 00:00:01
2017-01-01 02:00:00  0.994933  0.837652 2017-01-01 02:00:01
2017-01-01 04:00:00  0.925059  0.146704 2017-01-01 04:00:01
2017-01-01 06:00:00  0.269661  0.661669 2017-01-01 06:00:01
2017-01-01 08:00:00  0.528682  0.744998 2017-01-01 08:00:01

## KD Trees

In [100]:
from scipy.spatial import cKDTree

data1 = np.random.rand(100, 2)
data2 = np.random.rand(100, 2)

In [109]:
dates = pd.date_range('2012-01-01', freq='S', periods=20)
dates.values

array(['2012-01-01T00:00:00.000000000', '2012-01-01T00:00:01.000000000',
       '2012-01-01T00:00:02.000000000', '2012-01-01T00:00:03.000000000',
       '2012-01-01T00:00:04.000000000', '2012-01-01T00:00:05.000000000',
       '2012-01-01T00:00:06.000000000', '2012-01-01T00:00:07.000000000',
       '2012-01-01T00:00:08.000000000', '2012-01-01T00:00:09.000000000',
       '2012-01-01T00:00:10.000000000', '2012-01-01T00:00:11.000000000',
       '2012-01-01T00:00:12.000000000', '2012-01-01T00:00:13.000000000',
       '2012-01-01T00:00:14.000000000', '2012-01-01T00:00:15.000000000',
       '2012-01-01T00:00:16.000000000', '2012-01-01T00:00:17.000000000',
       '2012-01-01T00:00:18.000000000', '2012-01-01T00:00:19.000000000'], dtype='datetime64[ns]')

In [113]:
cKDTree(dates.values[:5, None]).query(dates.values[5:, None], 1)

(array([  1.00000000e+09,   2.00000000e+09,   3.00000000e+09,
          4.00000000e+09,   5.00000000e+09,   6.00000000e+09,
          7.00000000e+09,   8.00000000e+09,   9.00000000e+09,
          1.00000000e+10,   1.10000000e+10,   1.20000000e+10,
          1.30000000e+10,   1.40000000e+10,   1.50000000e+10]),
 array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]))

In [103]:
dist, ind = cKDTree(date).query(data2, 1)
data2[:5]

array([[ 0.57612072,  0.76737744],
       [ 0.0799649 ,  0.69987945],
       [ 0.19908587,  0.62064613],
       [ 0.93093536,  0.51156146],
       [ 0.10018539,  0.17617529]])

In [106]:
data1[ind[:5]]

array([[ 0.73317487,  0.5323165 ],
       [ 0.99773199,  0.15948563],
       [ 0.88927584,  0.76175311],
       [ 0.59267838,  0.60170377],
       [ 0.06988378,  0.36528017]])

In [107]:
dist[:5]

array([ 0.05974114,  0.00038318,  0.06907612,  0.02119608,  0.06519012])

Or this: http://stackoverflow.com/questions/33421551/how-to-merge-two-data-frames-based-on-nearest-date